### ISSUE TITLE
'index','glossary' in s:rst_accepted_dir_type

### ISSUE THREAD

**Issue by westurner** [ccwang002/dotvim#1]
``` vimrc
        " Setting for rst Linter
        let s:rst_accepted_dir_type =
                    \ '\(' .
                    \ 'seealso\|todo\|toctree\|' .
                    \ 'literalinclude\|' .
                    \ 'auto.*' .
                    \ '\)'
```

+'index\':
...

``` vimrc
        " Setting for rst Linter
        let s:rst_accepted_dir_type =
                    \ '\(' .
                    \ 'seealso\|todo\|toctree\|index\|' .
                    \ 'literalinclude\|' .
                    \ 'auto.*' .
                    \ '\)'
```

**Comment by westurner** [comment]
- https://github.com/westurner/dotvim/commit/39df6a3c64a6ac1d947f2b958116104e75f5afd3 + index
- https://github.com/westurner/dotvim/commit/c23d7660557848a956dec8557a024ec3cfc05d44 + glossary, term
- ... https://github.com/scrooloose/syntastic/issues/1195

**Comment by westurner** [comment]
... https://github.com/yoloseem/awesome-sphinxdoc :+1:

**Comment by ccwang002** [comment]
I only tried to make my rst linter less noisy by adding those directives, but I think the approach of using rstcheck is better and less hacky. Thanks for your help and the information!

**Comment by westurner** [comment]
Thanks!
